version: '3.1'

services:
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            APP_ENV: local
            COMPOSER_ALLOW_SUPERUSER: 1
            PHP_IDE_CONFIG: "serverName=pwa"
        ports:
            - "12001:12001"
        depends_on:
            - database

    database:
        image: mysql:5.6
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_USER=pwa
            - MYSQL_HOST=localhost
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - "33061:3306"

volumes:
    dbdata:
    storage:
